/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package kantin;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author yusuf
 */
public class Bakiye extends javax.swing.JFrame {

    Kantin k;
    DefaultTableModel dtm = new DefaultTableModel();
    DefaultTableModel dtm2 = new DefaultTableModel();
    double toplamAlacak;
    double toplamBakiye;

    /**
     * Creates new form Bakiye
     */
    public Bakiye() {
        initComponents();
    }

    public Bakiye(Kantin k) {
        initComponents();
        this.k = k;
        dtm.setColumnIdentifiers(new String[]{"Müşteri No", " Müşteri Adı", "Bakiye"});
        dtm2.setColumnIdentifiers(new String[]{"Tarih", "Müşteri No", "Müşteri Adi", "İşlem Türü", "Miktar"});
        tablo.setModel(dtm);
        tabloBakiyeIslem.setModel(dtm2);
        listele();
        toplamFiyatlar();
       
    }

    public void listele() {
         if (dtm.getRowCount() > 0) {
            for (int i = dtm.getRowCount() - 1; i > -1; i--) {
                dtm.removeRow(i);
            }
        }
        System.out.println(k.musteriler.size());
        for (MusteriA m : k.musteriler) {
            dtm.addRow(new String[]{"" + (m.no), m.isim, "" + m.bakiye});
            System.out.println("a");
        }
        System.out.println("aaaaaa");
    }

    public void toplamFiyatlar() {
        toplamAlacak=0;
        toplamBakiye=0;
        for (int i = 0; i < k.musteriler.size(); i++) {
            if (k.musteriler.get(i).bakiye < 0) {
                toplamAlacak -= k.musteriler.get(i).bakiye;
            } else {
                toplamBakiye += k.musteriler.get(i).bakiye;
            }
        }
         labelToplamAlacak.setText(String.valueOf(toplamAlacak));
         labelToplamBakiye.setText(String.valueOf(toplamBakiye));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        MusteriEkle = new javax.swing.JButton();
        BakiyeTanimla = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablo = new javax.swing.JTable();
        MusteriSil = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabloBakiyeIslem = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        labelToplamBakiye = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        labelToplamAlacak = new javax.swing.JLabel();
        bakiyeIade = new javax.swing.JButton();
        islemSil = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        bakiyegirisi = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 102));
        jPanel1.setPreferredSize(new java.awt.Dimension(1000, 555));

        MusteriEkle.setBackground(new java.awt.Color(51, 0, 102));
        MusteriEkle.setFont(new java.awt.Font("Arial Narrow", 1, 18)); // NOI18N
        MusteriEkle.setForeground(new java.awt.Color(255, 255, 255));
        MusteriEkle.setText("Müşteri Ekle");
        MusteriEkle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MusteriEkleActionPerformed(evt);
            }
        });

        BakiyeTanimla.setBackground(new java.awt.Color(51, 0, 102));
        BakiyeTanimla.setFont(new java.awt.Font("Arial Narrow", 1, 18)); // NOI18N
        BakiyeTanimla.setForeground(new java.awt.Color(255, 255, 255));
        BakiyeTanimla.setText("Bakiye Tanımla");
        BakiyeTanimla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BakiyeTanimlaActionPerformed(evt);
            }
        });

        tablo.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        tablo.setFont(new java.awt.Font("Arial Narrow", 1, 18)); // NOI18N
        tablo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tablo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabloMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablo);

        MusteriSil.setBackground(new java.awt.Color(51, 0, 102));
        MusteriSil.setFont(new java.awt.Font("Arial Narrow", 1, 18)); // NOI18N
        MusteriSil.setForeground(new java.awt.Color(255, 255, 255));
        MusteriSil.setText("Müsteri Sil");
        MusteriSil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MusteriSilActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(51, 0, 204));
        jButton1.setFont(new java.awt.Font("Arial Narrow", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Ana Menü");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        tabloBakiyeIslem.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        tabloBakiyeIslem.setFont(new java.awt.Font("Arial Narrow", 1, 18)); // NOI18N
        tabloBakiyeIslem.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabloBakiyeIslem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabloBakiyeIslemMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tabloBakiyeIslem);

        jLabel1.setFont(new java.awt.Font("Arial Narrow", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 255, 255));
        jLabel1.setText("Toplam Bakiye");

        labelToplamBakiye.setFont(new java.awt.Font("Arial Narrow", 1, 18)); // NOI18N
        labelToplamBakiye.setForeground(new java.awt.Color(102, 255, 255));

        jLabel2.setFont(new java.awt.Font("Arial Narrow", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 255, 255));
        jLabel2.setText("Toplam Alacak");

        labelToplamAlacak.setFont(new java.awt.Font("Arial Narrow", 1, 18)); // NOI18N
        labelToplamAlacak.setForeground(new java.awt.Color(102, 255, 255));

        bakiyeIade.setBackground(new java.awt.Color(51, 0, 102));
        bakiyeIade.setFont(new java.awt.Font("Arial Narrow", 1, 18)); // NOI18N
        bakiyeIade.setForeground(new java.awt.Color(255, 255, 255));
        bakiyeIade.setText("Bakiye İade");
        bakiyeIade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bakiyeIadeActionPerformed(evt);
            }
        });

        islemSil.setBackground(new java.awt.Color(51, 0, 102));
        islemSil.setFont(new java.awt.Font("Arial Narrow", 1, 18)); // NOI18N
        islemSil.setForeground(new java.awt.Color(255, 255, 255));
        islemSil.setText("İşlem Sil");
        islemSil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                islemSilActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Arial Narrow", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Copyright © Yusuf Nadir Uzun - Emre Yetkin 2020");

        bakiyegirisi.setBackground(new java.awt.Color(51, 0, 102));
        bakiyegirisi.setFont(new java.awt.Font("Arial Narrow", 1, 18)); // NOI18N
        bakiyegirisi.setForeground(new java.awt.Color(255, 255, 255));
        bakiyegirisi.setText("Bakiye Girişi");
        bakiyegirisi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bakiyegirisiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 793, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelToplamBakiye, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(5, 5, 5)
                                .addComponent(labelToplamAlacak, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addComponent(islemSil, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BakiyeTanimla, javax.swing.GroupLayout.DEFAULT_SIZE, 176, Short.MAX_VALUE)
                    .addComponent(bakiyeIade, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bakiyegirisi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jButton1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(MusteriSil, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(MusteriEkle, javax.swing.GroupLayout.DEFAULT_SIZE, 176, Short.MAX_VALUE)))
                .addGap(1, 1, 1))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel3))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addGap(12, 12, 12))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(bakiyegirisi, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(bakiyeIade, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BakiyeTanimla, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(islemSil, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
                        .addGap(41, 41, 41)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(MusteriEkle, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(MusteriSil, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                        .addGap(12, 12, 12)
                        .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelToplamBakiye, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
                                .addGap(1, 1, 1)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                            .addComponent(labelToplamAlacak, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(9, 9, 9))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addComponent(jLabel3))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BakiyeTanimlaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BakiyeTanimlaActionPerformed
        try {
             int a = JOptionPane.showConfirmDialog(null, " Bu işlem kasaya yansımayacak devam etmek istermisiniz ? " ,"Uyarı", JOptionPane.YES_NO_OPTION);
        if(a == 0){
            int no = Integer.parseInt((String) dtm.getValueAt(tablo.getSelectedRow(), 0));
            String bakiye = JOptionPane.showInputDialog(null,"Miktar giriniz", JOptionPane.INFORMATION_MESSAGE);
            if(bakiye!=null){
            k.bakiyeTanımla(no,Double.parseDouble(bakiye) );

         listele();
          toplamFiyatlar();
            }
               
        }
        } catch (ArrayIndexOutOfBoundsException e) {
            JOptionPane.showMessageDialog(null, "Listeden bakiye tanımlamak istediğiniz kişiyi seçiniz", "Uyarı", JOptionPane.WARNING_MESSAGE);
        }catch(NumberFormatException r){
             JOptionPane.showMessageDialog(null, "Yanlış deger girildi", "Uyarı", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_BakiyeTanimlaActionPerformed

    private void MusteriEkleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MusteriEkleActionPerformed
        String musteriIsim = JOptionPane.showInputDialog(null,"Müşteri Ismi giriniz", JOptionPane.INFORMATION_MESSAGE);
        if(musteriIsim!=null){
        k.musteriEkle(musteriIsim, 0);
        listele();
        }
        
    }//GEN-LAST:event_MusteriEkleActionPerformed

    private void MusteriSilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MusteriSilActionPerformed
        try {
             int a = JOptionPane.showConfirmDialog(null,"Müşteri silinsin mi ? ", "Uyarı", JOptionPane.WARNING_MESSAGE);
         if(a == 0){
            String no = (String) dtm.getValueAt(tablo.getSelectedRow(), 0);
            if (k.musteriSil(Integer.parseInt(no))) {
                dtm.removeRow(tablo.getSelectedRow());
                if (dtm2.getRowCount() > 0) {
                for (int i = dtm2.getRowCount() - 1; i > -1; i--) {
                    dtm2.removeRow(i);
                }
            }
            }
         }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Girdiğiniz bilgileri kontrol edin", "Uyarı", JOptionPane.WARNING_MESSAGE);
        } catch (ArrayIndexOutOfBoundsException w) {
            JOptionPane.showMessageDialog(null, "Listeden silmek istediğiniz kişiyi seçiniz", "Uyarı", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_MusteriSilActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Menu m = new Menu(k);
        m.setVisible(true);
        m.setLocationRelativeTo(null);
        setVisible(false);

    }//GEN-LAST:event_jButton1ActionPerformed

    private void tabloBakiyeIslemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabloBakiyeIslemMouseClicked

    }//GEN-LAST:event_tabloBakiyeIslemMouseClicked

    private void tabloMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabloMouseClicked
        int musteriNo = Integer.parseInt((String) dtm.getValueAt(tablo.getSelectedRow(), 0));
        if (k.bakiyeIslemler.size() != 0) {
            if (dtm2.getRowCount() > 0) {
                for (int i = dtm2.getRowCount() - 1; i > -1; i--) {
                    dtm2.removeRow(i);
                }
            }
            for (int i = 0; i < k.bakiyeIslemler.size(); i++) {
                if (k.bakiyeIslemler.get(i).MusteriNo == musteriNo) {
                    dtm2.addRow(new String[]{k.bakiyeIslemler.get(i).tarih, String.valueOf(k.bakiyeIslemler.get(i).MusteriNo), k.bakiyeIslemler.get(i).musteriAdi, k.bakiyeIslemler.get(i).tur + "", String.valueOf(k.bakiyeIslemler.get(i).para)});
                }
            }
            tabloBakiyeIslem.setModel(dtm2);
        }

    }//GEN-LAST:event_tabloMouseClicked

    private void bakiyeIadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bakiyeIadeActionPerformed
     try{
        String id = (String)dtm.getValueAt(tablo.getSelectedRow(), 0);
        String tutar = JOptionPane.showInputDialog(null, "İade edilecek tutar giriniz ", "tutar", JOptionPane.INFORMATION_MESSAGE);
        if(tutar!=null&&Double.parseDouble(tutar)>0){
        k.bakiyeIade(Integer.parseInt(id),-Double.parseDouble(tutar));
        listele();
         toplamFiyatlar();
        }else{
             JOptionPane.showMessageDialog(null, "Pozitif değer giriniz, işlem gerçekleşmedi", "Uyarı", JOptionPane.WARNING_MESSAGE);
        }
     }catch(ArrayIndexOutOfBoundsException r ){
          JOptionPane.showMessageDialog(null, "Listeden bakiye iadesi yapmak istediğiniz kişiyi seçiniz", "Uyarı", JOptionPane.WARNING_MESSAGE);
     }catch(NumberFormatException e){
            JOptionPane.showMessageDialog(null, "Girdiğiniz degerleri kontrol ediniz.", "uyarı", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_bakiyeIadeActionPerformed

    private void islemSilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_islemSilActionPerformed
  try{ 
       int a = JOptionPane.showConfirmDialog(null,"İşlem silinsin mi ? ", "Uyarı", JOptionPane.WARNING_MESSAGE);
         if(a == 0){
      String miktar = (String)dtm2.getValueAt(tabloBakiyeIslem.getSelectedRow(), 4);
       String tur = (String)dtm2.getValueAt(tabloBakiyeIslem.getSelectedRow(), 3);
       String tarih = (String)dtm2.getValueAt(tabloBakiyeIslem.getSelectedRow(), 0);
       String musteriNo = (String)dtm2.getValueAt(tabloBakiyeIslem.getSelectedRow(), 1);
        if(k.bakiyeIslemSil(tarih, tur, Double.parseDouble(miktar),Integer.parseInt(musteriNo))){
            dtm2.removeRow(tabloBakiyeIslem.getSelectedRow());
        listele();
         toplamFiyatlar();
        }
    }}catch(ArrayIndexOutOfBoundsException e){
        JOptionPane.showMessageDialog(null, "Listeden silmek istediğiniz işlemi listeden seçiniz");
    }
        
    }//GEN-LAST:event_islemSilActionPerformed

    private void bakiyegirisiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bakiyegirisiActionPerformed
      try {
            int no = Integer.parseInt((String) dtm.getValueAt(tablo.getSelectedRow(), 0));
            String bakiye = JOptionPane.showInputDialog(null,"Miktar giriniz", JOptionPane.INFORMATION_MESSAGE);
            if(bakiye!=null&&Double.parseDouble(bakiye)>0){
            k.bakiyeGirisi(no,Double.parseDouble(bakiye) );

         listele();
         toplamFiyatlar();
         }else{
             JOptionPane.showMessageDialog(null, "Pozitif değer giriniz, işlem gerçekleşmedi", "Uyarı", JOptionPane.WARNING_MESSAGE);
        }
        } catch (ArrayIndexOutOfBoundsException e) {
            JOptionPane.showMessageDialog(null, "Listeden bakiye tanımlamak istediğiniz kişiyi seçiniz", "Uyarı", JOptionPane.WARNING_MESSAGE);
        }catch(NumberFormatException e){
            JOptionPane.showMessageDialog(null, "Girdiğiniz degerleri kontrol ediniz.", "uyarı", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_bakiyegirisiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Bakiye.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Bakiye.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Bakiye.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Bakiye.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Bakiye().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BakiyeTanimla;
    private javax.swing.JButton MusteriEkle;
    private javax.swing.JButton MusteriSil;
    private javax.swing.JButton bakiyeIade;
    private javax.swing.JButton bakiyegirisi;
    private javax.swing.JButton islemSil;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel labelToplamAlacak;
    private javax.swing.JLabel labelToplamBakiye;
    private javax.swing.JTable tablo;
    private javax.swing.JTable tabloBakiyeIslem;
    // End of variables declaration//GEN-END:variables
}
