/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package kantin;

import java.text.SimpleDateFormat;
import java.util.GregorianCalendar;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author yusuf
 */
public class Kasa extends javax.swing.JFrame {

    DefaultTableModel dtm = new DefaultTableModel();
    Kantin k;
    double toplamAlacak;
    double toplamBakiye;
    double bulunanToplamPara;
    SimpleDateFormat bicim3 = new SimpleDateFormat("dd-MM-yyyy");
    GregorianCalendar gcalender = new GregorianCalendar();
    String tarih = bicim3.format(gcalender.getTime());

    /**
     * Creates new form Kasa
     */
    public Kasa() {
        initComponents();

    }

    public Kasa(Kantin k) {
        initComponents();
        this.k = k;
        dtm.setColumnIdentifiers(new String[]{"Tarih", "Tür", "Açıklama", "Para Miktari"});
        tabloKasa.setModel(dtm);
        listele();
        toplamFiyatlar();
        labelToplamPara.setText(String.valueOf(bulunanToplamPara));
        labelToplamAlacak.setText(String.valueOf(toplamAlacak));
        labelToplamBakiye.setText(String.valueOf(toplamBakiye));
    }

    public void listele() {
          if (dtm.getRowCount() > 0) {
            for (int i = dtm.getRowCount() - 1; i > -1; i--) {
                dtm.removeRow(i);
            }
        }
        for (int i = 0; i < k.kasaIslemler.size(); i++) {
            dtm.addRow(new String[]{k.kasaIslemler.get(i).tarih, k.kasaIslemler.get(i).tur, k.kasaIslemler.get(i).aciklama, String.valueOf(k.kasaIslemler.get(i).para)});
        }
    }

    public void toplamFiyatlar() {
        toplamAlacak=0;
        toplamBakiye=0;
        bulunanToplamPara = 0;
        for (int i = 0; i < k.musteriler.size(); i++) {
            if (k.musteriler.get(i).bakiye < 0) {
                toplamAlacak -= k.musteriler.get(i).bakiye;
            } else {
                toplamBakiye += k.musteriler.get(i).bakiye;
            }
        }
        
        for (int i = 0; i < k.kasaIslemler.size(); i++) {
            if (k.kasaIslemler.get(i).tur.equals("giris")) {
                bulunanToplamPara += k.kasaIslemler.get(i).para;
            } else {
                bulunanToplamPara += k.kasaIslemler.get(i).para;
            }
        }
          labelToplamPara.setText(String.valueOf(bulunanToplamPara));
        labelToplamAlacak.setText(String.valueOf(toplamAlacak));
        labelToplamBakiye.setText(String.valueOf(toplamBakiye));
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabloKasa = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        labelToplamPara = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        ParaEkle = new javax.swing.JButton();
        paraCikar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        labelToplamAlacak = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        labelToplamBakiye = new javax.swing.JLabel();
        IslemSil = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 0, 102));
        jPanel1.setPreferredSize(new java.awt.Dimension(1000, 555));

        tabloKasa.setFont(new java.awt.Font("Arial Narrow", 1, 18)); // NOI18N
        tabloKasa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tabloKasa);

        jLabel1.setFont(new java.awt.Font("Arial Narrow", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 255, 255));
        jLabel1.setText("İşlemler");

        jLabel2.setFont(new java.awt.Font("Arial Narrow", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 255, 255));
        jLabel2.setText("Kantindeki Toplam Para:");

        labelToplamPara.setFont(new java.awt.Font("Arial Narrow", 1, 18)); // NOI18N
        labelToplamPara.setForeground(new java.awt.Color(51, 255, 255));

        jButton1.setBackground(new java.awt.Color(51, 0, 204));
        jButton1.setFont(new java.awt.Font("Arial Narrow", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Ana Menu");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        ParaEkle.setBackground(new java.awt.Color(51, 0, 102));
        ParaEkle.setFont(new java.awt.Font("Arial Narrow", 1, 18)); // NOI18N
        ParaEkle.setForeground(new java.awt.Color(255, 255, 255));
        ParaEkle.setText("Para Girişi");
        ParaEkle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ParaEkleActionPerformed(evt);
            }
        });

        paraCikar.setBackground(new java.awt.Color(51, 0, 102));
        paraCikar.setFont(new java.awt.Font("Arial Narrow", 1, 18)); // NOI18N
        paraCikar.setForeground(new java.awt.Color(255, 255, 255));
        paraCikar.setText("Para Çıkışı");
        paraCikar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paraCikarActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Arial Narrow", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 255, 255));
        jLabel3.setText("Toplam Alacaklar");

        labelToplamAlacak.setFont(new java.awt.Font("Arial Narrow", 1, 18)); // NOI18N
        labelToplamAlacak.setForeground(new java.awt.Color(51, 255, 255));

        jLabel4.setFont(new java.awt.Font("Arial Narrow", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 255, 255));
        jLabel4.setText("Toplam Bakiye");

        labelToplamBakiye.setFont(new java.awt.Font("Arial Narrow", 1, 18)); // NOI18N
        labelToplamBakiye.setForeground(new java.awt.Color(0, 255, 255));

        IslemSil.setBackground(new java.awt.Color(51, 0, 102));
        IslemSil.setFont(new java.awt.Font("Arial Narrow", 1, 18)); // NOI18N
        IslemSil.setForeground(new java.awt.Color(255, 255, 255));
        IslemSil.setText("İşlem Sil");
        IslemSil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IslemSilActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(555, 555, 555))
                            .addComponent(jScrollPane1)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(labelToplamPara, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(labelToplamBakiye, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(60, 60, 60)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(548, 548, 548)
                                        .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addGap(224, 224, 224)
                                        .addComponent(IslemSil, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(47, 47, 47)
                                        .addComponent(paraCikar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(33, 33, 33)
                                        .addComponent(ParaEkle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(labelToplamAlacak, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addGap(42, 42, 42))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 306, Short.MAX_VALUE)
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(IslemSil, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addComponent(paraCikar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(ParaEkle, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(1, 1, 1))
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labelToplamPara, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelToplamAlacak, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE))
                .addGap(8, 8, 8)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labelToplamBakiye, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(23, 23, 23))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Menu m = new Menu(k);
        setVisible(false);
        m.setVisible(true);
        m.setLocationRelativeTo(null);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void ParaEkleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ParaEkleActionPerformed
      try{
        String miktar = JOptionPane.showInputDialog(null, "Miktar Giriniz", JOptionPane.INFORMATION_MESSAGE);
        String aciklama = JOptionPane.showInputDialog(null, "Açıklama Giriniz", JOptionPane.INFORMATION_MESSAGE);
        if(miktar!=null&&aciklama!=null&&Double.parseDouble(miktar)>0){
        k.kasaIslemEkle(tarih, "Kasa Girişi", aciklama, Double.parseDouble(miktar));
        listele();
            toplamFiyatlar();
             }
        else{
          JOptionPane.showMessageDialog(null, "İşlem gerçekleşmedi, girdiğiniz değerleri kontrol ediniz!");  
        }
      }catch(NumberFormatException e){
            JOptionPane.showMessageDialog(null, "Girdiğiniz degerleri kontrol ediniz.", "uyarı", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_ParaEkleActionPerformed

    private void paraCikarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paraCikarActionPerformed
      try{
        String miktar = JOptionPane.showInputDialog(null, "Miktar Giriniz", JOptionPane.INFORMATION_MESSAGE);
        String aciklama = JOptionPane.showInputDialog(null, "Açıklama Giriniz", JOptionPane.INFORMATION_MESSAGE);
        if(miktar!=null&&aciklama!=null&&Double.parseDouble(miktar)>0){
        k.kasaIslemEkle(tarih, "Kasa Çıkışı", aciklama, -Double.parseDouble(miktar));
       listele();
       toplamFiyatlar();
        }
        else{
          JOptionPane.showMessageDialog(null, "İşlem gerçekleşmedi, girdiğiniz değerleri kontrol ediniz!");  
        }
      }catch(NumberFormatException e){
            JOptionPane.showMessageDialog(null, "Girdiğiniz degerleri kontrol ediniz.", "uyarı", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_paraCikarActionPerformed

    private void IslemSilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IslemSilActionPerformed
        try {
         int a = JOptionPane.showConfirmDialog(null,"İşlem silinsin mi ? ", "Uyarı", JOptionPane.WARNING_MESSAGE);
         if(a == 0){
            String tarih = (String) dtm.getValueAt(tabloKasa.getSelectedRow(), 0);
            String tur = (String) dtm.getValueAt(tabloKasa.getSelectedRow(), 1);
            String aciklama = (String) dtm.getValueAt(tabloKasa.getSelectedRow(), 2);
         
                if (k.kasaIslemSil(tarih, tur, aciklama)) {
                dtm.removeRow(tabloKasa.getSelectedRow());
                }
                listele();
            toplamFiyatlar();
         }
        } catch (ArrayIndexOutOfBoundsException e) {
            JOptionPane.showMessageDialog(null, "Listeden İşlem Seçiniz", " Uyarı", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_IslemSilActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Kasa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Kasa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Kasa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Kasa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Kasa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton IslemSil;
    private javax.swing.JButton ParaEkle;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelToplamAlacak;
    private javax.swing.JLabel labelToplamBakiye;
    private javax.swing.JLabel labelToplamPara;
    private javax.swing.JButton paraCikar;
    private javax.swing.JTable tabloKasa;
    // End of variables declaration//GEN-END:variables
}
