/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package kantin;

import java.text.SimpleDateFormat;
import java.util.GregorianCalendar;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author yusuf
 */
public class Stok extends javax.swing.JFrame {

    Kantin k;

    /**
     * Creates new form Stok
     */
    SimpleDateFormat bicim3 = new SimpleDateFormat("dd-MM-yyyy");
    GregorianCalendar gcalender = new GregorianCalendar();
    String tarih = bicim3.format(gcalender.getTime());
    DefaultTableModel dtm = new DefaultTableModel();
    DefaultTableModel dtm2 = new DefaultTableModel();
    static Stok stok = new Stok();

    public Stok() {
        initComponents();

    }

    public Stok(Kantin k) {
        initComponents();
        this.k = k;
        dtm.setColumnIdentifiers(new String[]{"Stok No", "Ürün adı", "Ürün Miktarı",  "Ürün Alış Fiyatı","Ürün Satış Fiyatı"});
        dtm2.setColumnIdentifiers(new String[]{"Tarih", "Stok No", "İşlem Türü", "Miktar", "Açıklama"});

      
        tabloStok.setModel(dtm);
        tabloIslem.setModel(dtm2);
        listele();

    }

    public void listele() {

        if (dtm.getRowCount() > 0) {
            for (int i = dtm.getRowCount() - 1; i > -1; i--) {
                dtm.removeRow(i);
            }
        }
        for (UrunA u : k.urunler) {
           dtm.addRow(new String[]{String.valueOf(u.stokNumarasi), u.ad, String.valueOf(u.adet), String.valueOf(u.Alisfiyat),String.valueOf(u.Satisfiyat)});
        }

    }
    
    public void islemtablolistele(int stokno){
        if(k.stokIslemler.size() != 0){
         if (dtm2.getRowCount() > 0) {
            for (int i = dtm2.getRowCount() - 1; i > -1; i--) {
                dtm2.removeRow(i);
            }
        }
        for (int i = 0; i < k.stokIslemler.size(); i++) {
            if (k.stokIslemler.get(i).stokNo == stokno) {
                dtm2.addRow(new String[]{k.stokIslemler.get(i).tarih, k.stokIslemler.get(i).stokNo + "", k.stokIslemler.get(i).tur, k.stokIslemler.get(i).adet + "", k.stokIslemler.get(i).acıklama});
            }
        }
        tabloIslem.setModel(dtm2);
    }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabloStok = new javax.swing.JTable();
        YeniUrunEkle = new javax.swing.JButton();
        stokEkle = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        FiyatGuncelle = new javax.swing.JButton();
        Yenile = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabloIslem = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        stokCikisi = new javax.swing.JButton();
        IslemSil = new javax.swing.JButton();
        txtBarkod = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 0, 102));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(1000, 555));

        tabloStok.setFont(new java.awt.Font("Arial Narrow", 1, 18)); // NOI18N
        tabloStok.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabloStok.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabloStokMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabloStok);

        YeniUrunEkle.setBackground(new java.awt.Color(51, 0, 102));
        YeniUrunEkle.setFont(new java.awt.Font("Arial Narrow", 1, 18)); // NOI18N
        YeniUrunEkle.setForeground(new java.awt.Color(255, 255, 255));
        YeniUrunEkle.setText("Yeni ürün ekle");
        YeniUrunEkle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                YeniUrunEkleActionPerformed(evt);
            }
        });
        YeniUrunEkle.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                YeniUrunEkleKeyTyped(evt);
            }
        });

        stokEkle.setBackground(new java.awt.Color(51, 0, 102));
        stokEkle.setFont(new java.awt.Font("Arial Narrow", 1, 18)); // NOI18N
        stokEkle.setForeground(new java.awt.Color(255, 255, 255));
        stokEkle.setText("Stok Girişi");
        stokEkle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stokEkleActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(51, 0, 204));
        jButton3.setFont(new java.awt.Font("Arial Narrow", 1, 18)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Ana menü");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        FiyatGuncelle.setBackground(new java.awt.Color(51, 0, 102));
        FiyatGuncelle.setFont(new java.awt.Font("Arial Narrow", 1, 18)); // NOI18N
        FiyatGuncelle.setForeground(new java.awt.Color(255, 255, 255));
        FiyatGuncelle.setText("Ürün Düzenle");
        FiyatGuncelle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FiyatGuncelleActionPerformed(evt);
            }
        });

        Yenile.setBackground(new java.awt.Color(51, 0, 102));
        Yenile.setFont(new java.awt.Font("Arial Narrow", 1, 18)); // NOI18N
        Yenile.setForeground(new java.awt.Color(255, 255, 255));
        Yenile.setText("Yenile");
        Yenile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                YenileActionPerformed(evt);
            }
        });

        tabloIslem.setFont(new java.awt.Font("Arial Narrow", 1, 18)); // NOI18N
        tabloIslem.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tabloIslem);

        jButton1.setBackground(new java.awt.Color(51, 0, 102));
        jButton1.setFont(new java.awt.Font("Arial Narrow", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Ürün Sil");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        stokCikisi.setBackground(new java.awt.Color(51, 0, 102));
        stokCikisi.setFont(new java.awt.Font("Arial Narrow", 1, 18)); // NOI18N
        stokCikisi.setForeground(new java.awt.Color(255, 255, 255));
        stokCikisi.setText("Stok Çıkışı");
        stokCikisi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stokCikisiActionPerformed(evt);
            }
        });

        IslemSil.setBackground(new java.awt.Color(51, 0, 102));
        IslemSil.setFont(new java.awt.Font("Arial Narrow", 1, 18)); // NOI18N
        IslemSil.setForeground(new java.awt.Color(255, 255, 255));
        IslemSil.setText("İşlem Sil");
        IslemSil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IslemSilActionPerformed(evt);
            }
        });

        txtBarkod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBarkodActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Arial Narrow", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Barkod Numarası:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 668, Short.MAX_VALUE)
                    .addComponent(jScrollPane2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Yenile, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(FiyatGuncelle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(YeniUrunEkle, javax.swing.GroupLayout.DEFAULT_SIZE, 261, Short.MAX_VALUE)
                    .addComponent(stokEkle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(stokCikisi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(IslemSil, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtBarkod, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(36, 36, 36))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtBarkod, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(YeniUrunEkle, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(stokEkle, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(stokCikisi, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE)
                        .addGap(11, 11, 11))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addGap(4, 4, 4)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(IslemSil, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(FiyatGuncelle, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(Yenile, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                        .addGap(19, 19, 19)
                        .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
                        .addGap(30, 30, 30)
                        .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                .addGap(44, 44, 44))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        Menu menu = new Menu(k);
        setVisible(false);
        menu.setVisible(true);
        menu.setLocationRelativeTo(null);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void YeniUrunEkleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_YeniUrunEkleActionPerformed
        
        UrunEkle ue = new UrunEkle(k, stok);
        ue.setVisible(true);
        ue.setLocationRelativeTo(null);
       listele();
    }//GEN-LAST:event_YeniUrunEkleActionPerformed

    private void stokEkleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stokEkleActionPerformed

        try {
            int stokNok = Integer.parseInt((String) dtm.getValueAt(tabloStok.getSelectedRow(), 0));
            String adet = JOptionPane.showInputDialog(null,"Adet giriniz", JOptionPane.INFORMATION_MESSAGE);
            String aciklama = JOptionPane.showInputDialog(null,"Açıklama giriniz", JOptionPane.INFORMATION_MESSAGE);
             if(adet!=null&&aciklama!=null&&Double.parseDouble(adet)>0){
            k.stokEkle(stokNok, Integer.parseInt(adet), aciklama);
            islemtablolistele(stokNok);
          //  listele();
          }
        else{
          JOptionPane.showMessageDialog(null, "İşlem gerçekleşmedi, girdiğiniz değerleri kontrol ediniz!");  
        }
        } catch (ArrayIndexOutOfBoundsException e) {
            JOptionPane.showMessageDialog(null, "Listeden urun seçiniz", "uyarı", JOptionPane.WARNING_MESSAGE);
        }catch(NumberFormatException e){
            JOptionPane.showMessageDialog(null, "Girdiğiniz degerleri kontrol ediniz.", "uyarı", JOptionPane.WARNING_MESSAGE);
        }
        
    }//GEN-LAST:event_stokEkleActionPerformed

    private void FiyatGuncelleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FiyatGuncelleActionPerformed
 try{
        int stokNo = Integer.parseInt((String) dtm.getValueAt(tabloStok.getSelectedRow(), 0));
        UrunGuncelle ug = new UrunGuncelle(k, stokNo);
        ug.setVisible(true);
        ug.setLocationRelativeTo(null);
 }catch(ArrayIndexOutOfBoundsException e){
       JOptionPane.showMessageDialog(null, "Listeden urun seçiniz", "uyarı", JOptionPane.WARNING_MESSAGE);
 }
    }//GEN-LAST:event_FiyatGuncelleActionPerformed

    private void YenileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_YenileActionPerformed

        listele();
    }//GEN-LAST:event_YenileActionPerformed

    private void YeniUrunEkleKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_YeniUrunEkleKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_YeniUrunEkleKeyTyped

    private void tabloStokMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabloStokMouseClicked
    
        int stokNo = Integer.parseInt((String) dtm.getValueAt(tabloStok.getSelectedRow(), 0));
        islemtablolistele(stokNo);
  /*  if(k.stokIslemler.size() != 0){
         if (dtm2.getRowCount() > 0) {
            for (int i = dtm2.getRowCount() - 1; i > -1; i--) {
                dtm2.removeRow(i);
            }
        }
        for (int i = 0; i < k.stokIslemler.size(); i++) {
            if (k.stokIslemler.get(i).stokNo == stokNo) {
                dtm2.addRow(new String[]{k.stokIslemler.get(i).tarih, k.stokIslemler.get(i).stokNo + "", k.stokIslemler.get(i).tur, k.stokIslemler.get(i).adet + "", k.stokIslemler.get(i).acıklama});
            }
        }
        tabloIslem.setModel(dtm2);
    } */
        
    }//GEN-LAST:event_tabloStokMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
   try{   
        int a = JOptionPane.showConfirmDialog(null,"Ürün silinsin mi ? ", "Uyarı", JOptionPane.WARNING_MESSAGE);
         if(a == 0){
        int stokNo = Integer.parseInt((String) dtm.getValueAt(tabloStok.getSelectedRow(), 0));
         k.urunSil(stokNo);
         listele();
           if (dtm2.getRowCount() > 0) {
            for (int i = dtm2.getRowCount() - 1; i > -1; i--) {
                dtm2.removeRow(i);
            }
        }
         }
   }catch(ArrayIndexOutOfBoundsException e){
      JOptionPane.showMessageDialog(null, "Listeden silmek istediğiniz ürünü listeden seçiniz");
              }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void stokCikisiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stokCikisiActionPerformed
      try{ 
        int stokNok = Integer.parseInt((String) dtm.getValueAt(tabloStok.getSelectedRow(), 0));
        String adet = JOptionPane.showInputDialog(null, "Urun adedi", "Stok Çıkışı", JOptionPane.INFORMATION_MESSAGE);
         String aciklama = JOptionPane.showInputDialog(null, "Açıklama", "Stok Çıkışı", JOptionPane.INFORMATION_MESSAGE);
        if(adet!=null&&aciklama!=null&&Double.parseDouble(adet)>0){
        
        k.stokCikisi(stokNok,-Integer.parseInt(adet), aciklama);
        islemtablolistele(stokNok);
        }
        else{
          JOptionPane.showMessageDialog(null, "İşlem gerçekleşmedi, girdiğiniz değerleri kontrol ediniz!");  
        }
      }catch(ArrayIndexOutOfBoundsException e){
        JOptionPane.showMessageDialog(null, "Listeden silmek istediğiniz ürünü listeden seçiniz");
      }catch(NumberFormatException e){
            JOptionPane.showMessageDialog(null, "Girdiğiniz degerleri kontrol ediniz.", "uyarı", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_stokCikisiActionPerformed

    private void IslemSilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IslemSilActionPerformed
        try{
             int a = JOptionPane.showConfirmDialog(null,"İşlem silinsin mi ? ", "Uyarı", JOptionPane.WARNING_MESSAGE);
         if(a == 0){
            String tarih = (String)dtm2.getValueAt(tabloIslem.getSelectedRow(),0 );
            String aciklama = (String)dtm2.getValueAt(tabloIslem.getSelectedRow(),4 );
            String tur = (String)dtm2.getValueAt(tabloIslem.getSelectedRow(),2 );
            String stokNo = (String)dtm2.getValueAt(tabloIslem.getSelectedRow(),1 );
            if(k.stokIslemSil(aciklama, tur, tarih,Integer.parseInt(stokNo))){
              dtm2.removeRow(tabloIslem.getSelectedRow());
            }
         }
        }catch(ArrayIndexOutOfBoundsException r){
             JOptionPane.showMessageDialog(null, "Listeden silmek istediğiniz işlemi listeden seçiniz");
        }
    }//GEN-LAST:event_IslemSilActionPerformed

    private void txtBarkodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBarkodActionPerformed
       String barkodoku = txtBarkod.getText();
       txtBarkod.setText("");
       int sayac=0;
    /*   if(k.stokIslemler.size() != 0){
         if (dtm2.getRowCount() > 0) {
           for (int i = dtm2.getRowCount() - 1; i > -1; i--) {
                dtm2.removeRow(i);
            }
    } 
       }*/
      for(int i = 0; i < k.urunler.size(); i++){
           if ((k.urunler.get(i).barkod).equals(barkodoku) ) {
               int stokNo=k.urunler.get(i).stokNumarasi;
               
               System.out.println(tabloStok.getRowCount());
                System.out.println(k.urunler.get(i).stokNumarasi);  
              for(int j = 0; j < tabloStok.getRowCount();j++){
                  if(Integer.parseInt((String)dtm.getValueAt( j,0)) == stokNo){
                      System.out.println("j"+j);
                      tabloStok.clearSelection();
                      tabloStok.addRowSelectionInterval(j, j);
                      
                  } 
                  System.out.println(dtm.getValueAt( j,0));
              }
               islemtablolistele(stokNo);
            /*   
               for (int l = 0; l < k.stokIslemler.size(); l++) {
            if (k.stokIslemler.get(l).stokNo == stokNo) {
                dtm2.addRow(new String[]{k.stokIslemler.get(l).tarih, k.stokIslemler.get(l).stokNo + "", k.stokIslemler.get(l).tur, k.stokIslemler.get(l).adet + "", k.stokIslemler.get(l).acıklama});
            }
        }
        tabloIslem.setModel(dtm2);
        */
             sayac++;  
            
            
           }
           
          
      }
         if(sayac==0){
               JOptionPane.showMessageDialog(null, "Ürün bulunamadı.", "uyarı", JOptionPane.WARNING_MESSAGE);
           }
       
        
       
       
    }//GEN-LAST:event_txtBarkodActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Stok.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Stok.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Stok.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Stok.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                stok.setVisible(true);
                stok.setLocationRelativeTo(null);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton FiyatGuncelle;
    private javax.swing.JButton IslemSil;
    private javax.swing.JButton YeniUrunEkle;
    private javax.swing.JButton Yenile;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton stokCikisi;
    private javax.swing.JButton stokEkle;
    private javax.swing.JTable tabloIslem;
    private javax.swing.JTable tabloStok;
    private javax.swing.JTextField txtBarkod;
    // End of variables declaration//GEN-END:variables
}
